# Generated by Django 4.0.3 on 2022-03-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecorus_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='people_working',
        ),
        migrations.AddField(
            model_name='office',
            name='people_working',
            field=models.ManyToManyField(to='ecorus_api.person'),
        ),
    ]
